Hazelcast integration with Hikari connection pool
hazelcast/hazelcast-code-samples pull request #694
Opened 2024-12-01 16:49 UTC by rajangare

Hazelcast Integration with Hikari Connection Pool
To create Hikari connection pool, first create database table mapping with Hazelcast in-memory map.
In this demo, I have used EMPLOYEE table created on H2 DB, which is mapped with employee-map.

- Create Hikari data source from HikariConfig, with database credentials and connection pool configuration e.g. pool size, connection timeout etc.
- Get the connection from Hikari Data Source.
- Implement the Map Store Factory from MapLoader<K, V>, MapStore<K, V> and override all the necessary methods.
- Register the MapStore into hazelcast.xml config.
   
  
    <hazelcast>
     ...
        <map name="empaloyee_map">
           <map-store enabled="true">
             <class-name>com.demo.maps.EmployeeMapStore</class-name>
           </map-store>
        </map>
     ...
    </hazelcast>

Database connection information can be externalized from hazelcast.xml. Build the above classes in a jar and copy them inside Hazelcast user-lib directory under the Hazelcast installation.

2024-12-01 16:49 UTC, devOpsHazelcast commented
[![CLA assistant check](https://cla.hazelcast.org:443/pull/badge/not_signed)](https://cla.hazelcast.org:443/hazelcast/hazelcast-code-samples?pullRequest=694) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.hazelcast.org:443/hazelcast/hazelcast-code-samples?pullRequest=694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.hazelcast.org:443/check/hazelcast/hazelcast-code-samples?pullRequest=694) it.</sub>

2024-12-02 10:01 UTC, frant-hartm requested changes

2024-12-02 15:22 UTC, yuce requested changes
Thanks for the PR!
Just a few ideas...

2024-12-04 09:27 UTC, yuce commented
@rajangare Latest changes don't make this class thread-safe, but it would be good if you could add a comment that mentions this issue.

2024-12-04 12:08 UTC, rajangare commented
> @rajangare Latest changes don't make this class thread-safe, but it would be good if you could add a comment that mentions this issue.

@yuce added the comments on top, for thread-safe. do you have any suggestion to make it thread-safe please help here.

2024-12-06 13:30 UTC, merged